Repository DDD-Community/MorningBear-iOS, pull requests merged in 2022-12, with the labels that each got.

#11 [Feat] Add apple login manager
  MorningBear.entitlements
  Targets/MorningBear/Sources/AuthViewController.swift
  Targets/MorningBearKit/Sources/Auth/AppleLoginManager.swift
Labels: feature

#10 [Feature] Migrate image bucket(FirebaseStorage)
  Project.swift
  Targets/MorningBear/Resources/Asset.xcassets/AppIcon.appiconset/Contents.json
  Targets/MorningBear/Resources/Asset.xcassets/Contents.json
  Targets/MorningBear/Resources/Asset.xcassets/test.imageset/Contents.json
  Targets/MorningBear/Resources/Asset.xcassets/test.imageset/KakaoTalk_Photo_2022-11-24-13-09-01.png
  Targets/MorningBear/Resources/GoogleService-Info.plist
  Targets/MorningBear/Sources/AppDelegate.swift
  Targets/MorningBearKit/Sources/Reomte Storage/FirebaseStorageService.swift
  Targets/MorningBearKit/Sources/Reomte Storage/RemoteStorageManager.swift
  Targets/MorningBearKit/Sources/Reomte Storage/RemoteStoraging.swift
  Targets/MorningBearKit/Sources/Reomte Storage/StorageError.swift
  Targets/MorningBearKit/Tests/Remote Storage/RemoteStorageTests.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: feature

#15 [Resource] colors setting
  Targets/MorningBear/Resources/Colors.xcassets/CANCELED Dark.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/CANCELED Light.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/CANCELED.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Gray 100.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Gray 200.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Gray 300.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Gray 400.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Gray 50.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Gray 500.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Gray 700.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Gray 800.colorset/Contents.json
Labels: chore, resource

#16 [Feature] Connect API server with Apollo
  Local/GraphQL/MorningBearAPI/FindLoginInfo.graphql
  Local/GraphQL/MorningBearAPI/MorningBear.graphqls
  Local/GraphQL/MorningBearAPI/Package.swift
  Local/GraphQL/MorningBearAPI/Sources/Operations/Queries/FindLoginInfoQuery.graphql.swift
  Local/GraphQL/MorningBearAPI/Sources/Schema/Objects/LoginBaseInfo.graphql.swift
  Local/GraphQL/MorningBearAPI/Sources/Schema/Objects/Query.graphql.swift
  Local/GraphQL/MorningBearAPI/Sources/Schema/SchemaConfiguration.swift
  Local/GraphQL/MorningBearAPI/Sources/Schema/SchemaMetadata.graphql.swift
  Local/GraphQL/MorningBearAPI/TestMocks/LoginBaseInfo+Mock.graphql.swift
  Local/GraphQL/MorningBearAPI/TestMocks/Query+Mock.graphql.swift
  Local/GraphQL/MorningBearAPI/apollo-codegen-config.json
  Local/GraphQL/StarWarsAPI/AllFilmsQuery.graphql
  Local/GraphQL/StarWarsAPI/StarWarsAPI.json
  Local/GraphQL/StarWarsAPI/apollo-codegen-config.json
  Local/GraphQL/StarWarsAPI/registry_response.json
  Local/GraphQL/StarWarsAPI/star-wars-swapi@current.graphqls
  Targets/MorningBearKit/Sources/Network/API/GraphQL/Network.swift
  Targets/MorningBearKit/Tests/MorningBearKitTests.swift
  Targets/MorningBearKit/Tests/Network/GraphQLRequestTests.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: feature

#23 [Feature] Kakao login manager
  Targets/MorningBear/Sources/AppDelegate.swift
  Targets/MorningBear/Sources/AuthViewController.swift
  Targets/MorningBear/Sources/SceneDelegate.swift
  Targets/MorningBearKit/Sources/Auth/AppleLoginManager.swift
  Targets/MorningBearKit/Sources/Auth/KakaoLoginManager.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: feature

#31 Feat/setting entitlements
  Local/Entitlements/MorningBear.entitlements
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: chore, feature

#32 [Docs] Apply PR template at default branch
  .github/pull_request_template.md
Labels: docs

#33 [Feature] onboarding
  Targets/MorningBear/Resources/Colors.xcassets/Primary Color/Primary 100.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Primary Color/Primary 200.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Primary Color/Primary 300.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Primary Color/Primary 400.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Primary Color/Primary 50.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Primary Color/Primary 500.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Primary Color/Primary 600.colorset/Contents.json
  Targets/MorningBear/Resources/Colors.xcassets/Primary Color/Primary Default.colorset/Contents.json
  Targets/MorningBear/Sources/Onboarding/Onboarding.storyboard
  Targets/MorningBear/Sources/Onboarding/OnboardingCell.swift
  Targets/MorningBear/Sources/Onboarding/OnboardingData.swift
  Targets/MorningBear/Sources/Onboarding/OnboardingViewController.swift
  Targets/MorningBear/Sources/Onboarding/OnboardingViewModel.swift
  Targets/MorningBear/Sources/SceneDelegate.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: design, feature

#36 🐛 : Fix invalid variable name
  Targets/MorningBear/Sources/Onboarding/OnboardingCell.swift
Labels: bug

#46 [Feature] Layout login view
  Targets/MorningBear/Resources/Storyboard/Login.storyboard
  Targets/MorningBear/Sources/Login/AuthViewController.swift
  Targets/MorningBear/Sources/Onboarding/OnboardingViewController.swift
Labels: design, feature
