Repository DDD-Community/MorningBear-iOS, pull requests merged in 2023-01, with the labels that each got.

#66 [Design] Login View
  Targets/MorningBear/Resources/Storyboard/Login.storyboard
  Targets/MorningBear/Sources/Home/HomeViewController.swift
  Targets/MorningBear/Sources/Login/AuthViewController.swift
  Targets/MorningBear/Sources/Login/LoginViewController.swift
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Background/Primary Background.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Background/Secondary Background.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Background/Tertiary Background.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Background/Third Background.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Gray Scale/Gray 100.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Gray Scale/Gray 200.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Gray Scale/Gray 300.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Gray Scale/Gray 400.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Gray Scale/Gray 50.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Gray Scale/Gray 500.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Gray Scale/Gray 700.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Gray Scale/Gray 800.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Gray Scale/Gray 900.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Status Color/CANCELED Dark.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Status Color/CANCELED Light.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Status Color/CANCELED.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Status Color/Notice.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Text Color/Caption Text.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Text Color/Disabled Text.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Text Color/Primary Text.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Colors.xcassets/Text Color/Secondary Text.colorset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/AppIcon.appiconset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Contents.json
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/Contents.json
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/apple_button.imageset/Apple Button.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/apple_button.imageset/Apple Button@2x.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/apple_button.imageset/Apple Button@3x.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/apple_button.imageset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/kakao_button.imageset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/kakao_button.imageset/Kakao Button.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/kakao_button.imageset/Kakao Button@2x.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/kakao_button.imageset/Kakao Button@3x.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/logo.imageset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/logo.imageset/Group 7289.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/logo.imageset/Group 7289@2x.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/Login/logo.imageset/Group 7289@3x.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/back_arrow.imageset/Contents.json
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/back_arrow.imageset/back_arrow.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/back_arrow.imageset/back_arrow@2x.png
  Targets/MorningBearUI/Resources/Assets/Images.xcassets/back_arrow.imageset/back_arrow@3x.png
  Targets/MorningBearUI/Sources/Views/My badges/MyBadgeStateCell.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: design, resource

#71 [Feature] Token process
  Targets/MorningBear/Sources/Login/LoginViewController.swift
  Targets/MorningBearKit/Sources/Auth/AppleLoginManager.swift
  Targets/MorningBearKit/Sources/Auth/AuthUserDefaultsManager.swift
  Targets/MorningBearKit/Sources/Auth/KakaoLoginManager.swift
  Targets/MorningBearKit/Sources/Auth/TokenManager.swift
Labels: feature

#73 Feature/category view
  Targets/MorningBear/Resources/Storyboard/Home/RegisterMorning.storyboard
  Targets/MorningBear/Sources/Home/Register morning/Data/MorningRegistrationInfo.swift
  Targets/MorningBear/Sources/Home/Register morning/RegisterMorningViewController.swift
  Targets/MorningBear/Sources/Home/Register morning/RegisterMorningViewModel.swift
  Targets/MorningBear/Tests/Home/Register morning/RegisterMorningViewModelTests.swift
  Targets/MorningBearKit/Sources/DateFomatter/Date + Extension.swift
  Targets/MorningBearKit/Tests/DateExtensionTests.swift
  Targets/MorningBearUI/Resources/Cell/CapsuleCell.xib
  Targets/MorningBearUI/Sources/Utils/Compositional collection view/CompositionalLayoutProvider.swift
  Targets/MorningBearUI/Sources/Views/Common/Cell/CapsuleCell.swift
  Targets/MorningBearUI/Sources/Views/Common/Table view/Horizontal/HorizontalScrollCollectionViewProvider.swift
  Targets/MorningBearUI/Sources/Views/Common/Table view/Horizontal/HorizontalScrollableCellType.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: design, feature

#75 [Refactor] Register morning + Timer
  Targets/MorningBear/Resources/Storyboard/Home/Home.storyboard
  Targets/MorningBear/Sources/Home/HomeViewController.swift
  Targets/MorningBear/Sources/Home/HomeViewDataProvider.swift
  Targets/MorningBear/Sources/Home/HomeViewModel.swift
  Targets/MorningBear/Sources/Home/Register morning/RegisterMorningViewController.swift
  Targets/MorningBear/Sources/Home/Register morning/RegisterMorningViewModel.swift
  Targets/MorningBear/Sources/Protocol/DataProviding.swift
  Targets/MorningBear/Tests/Home/HomeDataProviderTests.swift
  Targets/MorningBear/Tests/Home/HomeViewModelTests.swift
  Targets/MorningBearKit/Sources/DateFomatter/MorningBearDateFormatter.swift
  Targets/MorningBearKit/Tests/MorningBearDateFormatterTests.swift
  Targets/MorningBearUI/Resources/Button/RecordingNowButton.xib
  Targets/MorningBearUI/Sources/Utils/UIView + Extension.swift
  Targets/MorningBearUI/Sources/Views/Common/Button/RecordingNowButton.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: bug, feature, refactor

#76 [Bug] Fix package version error
  Tuist/Dependencies.swift
Labels: bug

#91 [Design] Font extension
  Targets/MorningBearUI/Sources/Utils/Font/Font + Extension.swift
Labels: design, feature
